### ISSUE TITLE
分数上传失败

### ISSUE THREAD

**Issue by qq634421026** [xushanmeng/WechatJumpHelper#5]
跳完之后上传分数的时候，提示上传失败，应该是点击屏幕的坐标总是一个点，可能微信默认这种一直点击一个坐标是辅助器跳的，我把点击屏幕的坐标改成随机位置，就可以了

**Comment by xushanmeng** [comment]
多谢分享BUG，该问题已经修复

**Comment by qq634421026** [comment]
不客气
